[server]
host = "0.0.0.0"
port = 8000
mode = "development"

[database]
url = "postgres://postgres:postgres@localhost:5432/ara"
max_connections = 0
min_connections = 0

[jwt]
secret = "ara-json-web-token-secret"
expire_hours = 24

[log]
level = "info"
format = "console"
target = "ARA-API-DEV"
ansi = true

[swagger]
username = ""
password = ""
